import React from 'react';
import { Printer, ArrowLeft, CheckCircle, FileText } from 'lucide-react';
import { UserProfile, Scheme } from '../types';

interface KioskReportProps {
  profile: Partial<UserProfile>;
  schemes: Scheme[];
  onBack: () => void;
}

export const KioskReport: React.FC<KioskReportProps> = ({ profile, schemes, onBack }) => {
  const handlePrint = () => {
    window.print();
  };

  // Basic mock eligibility evaluation
  const eligibleSchemes = schemes.filter(s => {
    const isStateMatch = !s.eligibilityRules?.allowedStates || s.eligibilityRules.allowedStates.includes('All') || (profile.state && s.eligibilityRules.allowedStates.includes(profile.state));
    const isAgeMatch = (!s.eligibilityRules?.minAge || (profile.age && profile.age >= s.eligibilityRules.minAge)) &&
                       (!s.eligibilityRules?.maxAge || (profile.age && profile.age <= s.eligibilityRules.maxAge));
    return isStateMatch && isAgeMatch;
  });

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-[#07111F] text-slate-900 dark:text-slate-100 font-sans print:bg-white print:text-black">
      {/* Top action bar - Hidden during print */}
      <div className="bg-white dark:bg-[#0F1B2D] border-b border-slate-200 dark:border-slate-800 p-4 flex items-center justify-between print:hidden">
        <button onClick={onBack} className="flex items-center text-slate-500 hover:text-slate-900 dark:hover:text-white font-bold transition-colors">
          <ArrowLeft className="w-5 h-5 mr-2" /> Back to Search
        </button>
        <button onClick={handlePrint} className="flex items-center px-6 py-2 bg-primary text-white font-bold rounded-lg shadow hover:bg-blue-600 transition-colors">
          <Printer className="w-5 h-5 mr-2" /> Print PDF Report
        </button>
      </div>

      {/* Printable Area */}
      <div className="max-w-4xl mx-auto p-8 print:p-0">
        <div className="bg-white dark:bg-[#0F1B2D] border border-slate-200 dark:border-slate-800 rounded-xl shadow-sm print:shadow-none print:border-none p-8 md:p-12 print:p-0">
          
          {/* Document Header */}
          <div className="flex justify-between items-start border-b-2 border-slate-900 dark:border-white pb-6 mb-8 print:border-black">
            <div>
              <h1 className="text-3xl font-bold uppercase tracking-widest text-slate-900 dark:text-white print:text-black">GovScheme</h1>
              <p className="text-sm font-bold text-slate-500 print:text-black">Citizen Eligibility Report</p>
            </div>
            <div className="text-right text-sm text-slate-500 print:text-black font-medium space-y-1">
              <div>Date: {new Date().toLocaleDateString()}</div>
              <div>Generated by: CSC Digital Seva</div>
              <div>Ref ID: REP-{Math.floor(Math.random() * 1000000)}</div>
            </div>
          </div>

          {/* Citizen Details */}
          <div className="mb-10 p-6 bg-slate-50 dark:bg-[#16243A] rounded-xl print:bg-white print:border print:border-slate-300">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white print:text-black mb-4 uppercase tracking-wider">Beneficiary Profile</h2>
            <div className="grid grid-cols-2 md:grid-cols-3 gap-6 text-sm">
              <div>
                <div className="text-slate-500 mb-1 print:text-black font-semibold">Name</div>
                <div className="font-bold text-slate-900 dark:text-white print:text-black">{profile.fullName || 'N/A'}</div>
              </div>
              <div>
                <div className="text-slate-500 mb-1 print:text-black font-semibold">Age</div>
                <div className="font-bold text-slate-900 dark:text-white print:text-black">{profile.age || 'N/A'} yrs</div>
              </div>
              <div>
                <div className="text-slate-500 mb-1 print:text-black font-semibold">State</div>
                <div className="font-bold text-slate-900 dark:text-white print:text-black">{profile.state || 'N/A'}</div>
              </div>
              <div>
                <div className="text-slate-500 mb-1 print:text-black font-semibold">Mobile</div>
                <div className="font-bold text-slate-900 dark:text-white print:text-black">{profile.mobile || 'N/A'}</div>
              </div>
              <div>
                <div className="text-slate-500 mb-1 print:text-black font-semibold">Occupation</div>
                <div className="font-bold text-slate-900 dark:text-white print:text-black">{profile.occupation || 'N/A'}</div>
              </div>
              <div>
                <div className="text-slate-500 mb-1 print:text-black font-semibold">Annual Income</div>
                <div className="font-bold text-slate-900 dark:text-white print:text-black">₹{profile.annualIncome?.toLocaleString() || 'N/A'}</div>
              </div>
            </div>
          </div>

          {/* Evaluation Results */}
          <div className="mb-6 flex items-center gap-3">
             <div className="w-10 h-10 rounded-full bg-emerald-100 dark:bg-emerald-900/30 flex items-center justify-center print:bg-emerald-100">
               <CheckCircle className="w-6 h-6 text-emerald-600 dark:text-emerald-400 print:text-emerald-700" />
             </div>
             <div>
                <h2 className="text-xl font-bold text-slate-900 dark:text-white print:text-black">Eligible Schemes Found: {eligibleSchemes.length}</h2>
                <p className="text-sm text-slate-500 print:text-black">Based on the provided demographic data, the citizen qualifies for the following benefits.</p>
             </div>
          </div>

          {/* Scheme List */}
          <div className="space-y-6 mt-8">
            {eligibleSchemes.map((scheme, idx) => (
              <div key={scheme.id} className="p-6 border border-slate-200 dark:border-slate-800 rounded-xl print:border-slate-300 print:break-inside-avoid">
                <div className="flex justify-between items-start mb-2">
                   <h3 className="text-lg font-bold text-slate-900 dark:text-white print:text-black">{idx + 1}. {scheme.name}</h3>
                   <span className="px-3 py-1 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 print:bg-gray-100 print:text-black text-xs font-bold rounded-full">
                     {scheme.department}
                   </span>
                </div>
                <p className="text-sm text-slate-600 dark:text-slate-400 print:text-black mb-4">{scheme.shortDescription}</p>
                
                <div className="flex items-center gap-6 mt-4 pt-4 border-t border-slate-100 dark:border-slate-800 print:border-slate-200 text-sm">
                  <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-primary print:text-black" />
                    <span className="font-bold text-slate-900 dark:text-white print:text-black">Required Docs:</span>
                    <span className="text-slate-500 print:text-black">{scheme.requiredDocuments?.join(', ') || 'Standard KYC'}</span>
                  </div>
                </div>
              </div>
            ))}
            
            {eligibleSchemes.length === 0 && (
              <div className="p-8 text-center border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-xl print:border-slate-300 text-slate-500 print:text-black">
                No matching schemes found for this profile.
              </div>
            )}
          </div>

          <div className="mt-16 pt-8 border-t border-slate-200 dark:border-slate-800 print:border-slate-300 flex justify-between items-end text-sm text-slate-500 print:text-black break-inside-avoid">
             <div>
               <p className="font-bold mb-1">Disclaimer</p>
               <p className="max-w-md text-xs">This report is automatically generated based on user input and does not guarantee benefit disbursement. Final approval is subject to document verification by the respective department.</p>
             </div>
             <div className="text-right">
               <div className="w-48 border-b border-slate-400 mb-2 print:border-black"></div>
               <p>Authorized Signature</p>
             </div>
          </div>

        </div>
      </div>
    </div>
  );
};
